
  spring:
    application:
      name: online-chess
    cloud:
      compatibility-verifier:
        enabled: false
    datasource:
      url: jdbc:h2:~/chessdb
      driverClassName: org.h2.Driver
      username: sa
      password: password
      
    sql:
      init:
        mode: always
        data-locations:
        - classpath:/data.sql
        - classpath:/schema.sql
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: update
      show-sql: true
    h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          trace: false
          web-allow-others: false

  server:
    port: 8080

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
    server:
      enable-self-preservation: false

  management:
    endpoints:
      web:
        exposure:
          include: "*"
          
          
  logging:
    level:
      ROOT: DEBUG
